apiVersion: v1
kind: Template
metadata:
  name: 3scale-challenge
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "3scale-challenge"
    namespace: ${NAMESPACE}
  spec:
    source:
      git:
        uri: ${GIT_REPO}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: library_core/Jenkinsfile
        env:
          - name: SECRET_NAME
            value: ${SECRET_NAME}
          - name: NAMESPACE
            value: ${NAMESPACE}
          - name: TARGET_INSTANCE
            value: ${TARGET_INSTANCE}
          - name: DEVELOPER_ACCOUNT_ID
            value: ndobler
          - name: PRIVATE_BASE_URL
            value: ${PRIVATE_BASE_URL}
          - name: DISABLE_TLS_VALIDATION
            value: ${DISABLE_TLS_VALIDATION}
parameters:
- name: SECRET_NAME
  value: 3scale-toolbox
- name: NAMESPACE
  value: user10
- name: TARGET_INSTANCE
  value: 3scale-onprem
- name: GIT_REPO
  value: https://github.com/ndobler/library_Core.git
- name: DEVELOPER_ACCOUNT_ID
  required: true
- name: PRIVATE_BASE_URL
  required: true
- name: DISABLE_TLS_VALIDATION
  value: "no"